### PR TITLE
[FEATURE] MichalW Better EventContent

### PR DESCRIPTION
**Pull request by skrapi2011**
Changed EventContent appearance, added EventCard from figma
+ Compatibility with backend after #166 merge

image

### CODE REVIEW

**Comment by skrapi2011** [comment]
[zmiana eventcontent](https://trello.com/c/qth2pbIX/195-zmiana-eventcontent)

**Comment by Bambi54** [comment]
[wydarzenia w detalu restauracji](https://trello.com/c/qmUMBdba/192-wydarzenia-w-detalu-restauracji)

**Review by Bambi54 — CHANGES_REQUESTED** [review]
EventsContent, EventCard, MenuContent przenieś do RestaurantComponents

**Comment by Bambi54** [comment]
i zrób rebase

**Comment by Bambi54** [comment]
[EventActivity](https://trello.com/c/08kRamQl/184-eventactivity)

**Pull request merged**
